// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeshwzlcmufxuoznkdkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlc2h3emxjbXVmeHVvem5rZGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjg5OTYsImV4cCI6MjA2MjcwNDk5Nn0.2Du3sTgm8Q1IV-c8xvjAYUR2MEbQkht_EpCP7uX9iFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);